### ISSUE TITLE
Can't install on react@"^18.2.0"

### ISSUE THREAD

**Issue by acocmor** [dmh126/react-adsk-forge-viewer-ts#9]
Hi Damian Harasymczuk, 
I'm trying to install your package, but I have a problem with react@"^18.2.0"
![image](https://user-images.githubusercontent.com/96630540/195030936-744ecd63-3eb9-43b6-9e37-23cff4f54891.png)
Can you check again?

**Comment by dmh126** [comment]
Hello, 
What is your node version? It works fine with v14 for me in React 18.2.0 app bootstrapped with create-react-app.

**Comment by dmh126** [comment]
I checked the more recent versions and encountered the same problem. I rebuilt the package-lock.json and bumped the peer dependency version for React to 18 and now it's fine for Node 16, 18 etc. 

I published **version 1.1.7** that should be fine with new Node.

**Comment by acocmor** [comment]
Amazing, thanks !!
